name = "PlutoBook"
uuid = "76e9aec1-d984-498e-955d-b16e80c2ab71"
authors = ["Avik Sengupta and contributors"]
version = "1.2.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
PlutoBook_jll = "41d2b3ab-7676-5bec-847c-6e41a0c34141"

[compat]
CEnum = "0.5.0"
PlutoBook_jll = "0.12.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
